"""Utility functions for the SmartDocQ application."""

# Import utility modules for easier access
from .file_utils import (
    save_uploaded_file,
    get_file_metadata,
    delete_file,
    list_files,
    create_directory,
    get_file_extension,
    is_valid_document_extension,
    is_valid_image_extension,
    get_mime_type,
)

from .http_utils import (
    is_valid_url,
    normalize_url,
    get_domain,
    fetch_url,
    post_json,
    download_file,
    extract_urls_from_text,
)

from .text_utils import (
    normalize_text,
    clean_text,
    extract_keywords,
    calculate_text_stats,
    split_text_by_sentences,
    split_text_by_paragraphs,
    split_text_into_chunks,
    detect_language,
    summarize_text,
    find_similar_texts,
)

from .date_utils import (
    get_current_timestamp,
    get_current_datetime,
    format_datetime,
    parse_datetime,
    timestamp_to_datetime,
    datetime_to_timestamp,
    get_date_range,
    get_relative_date,
    format_time_ago,
    get_date_components,
    is_weekend,
    is_business_day,
    add_business_days,
    get_month_start_end,
    get_quarter_start_end,
    get_year_start_end,
)

from .validation_utils import (
    is_valid_email,
    is_valid_phone,
    is_valid_url,
    is_valid_ipv4,
    is_valid_ipv6,
    is_valid_ip,
    is_valid_username,
    is_valid_password,
    is_valid_hex_color,
    is_valid_isbn,
    is_valid_zip_code,
    is_valid_credit_card,
    is_valid_date,
    is_valid_json,
    validate_required_fields,
    validate_field_type,
    validate_string_length,
    validate_number_range,
    validate_list_length,
    validate_enum,
    validate_regex,
    validate_data,
    validate_and_raise,
)

from .security_utils import (
    generate_password_hash,
    verify_password,
    generate_token,
    decode_token,
    generate_api_key,
    generate_random_password,
    generate_random_string,
    hash_data,
    generate_salt,
    hash_password_with_salt,
    verify_password_with_salt,
    generate_secure_filename,
    sanitize_input,
    generate_csrf_token,
    generate_session_id,
    is_valid_api_key,
)

from .image_utils import (
    is_valid_image_extension,
    get_image_mime_type,
    open_image,
    open_image_from_bytes,
    save_image,
    image_to_bytes,
    resize_image,
    crop_image,
    rotate_image,
    adjust_brightness,
    adjust_contrast,
    adjust_sharpness,
    convert_to_grayscale,
    apply_blur,
    apply_threshold,
    enhance_image_for_ocr,
    detect_text_regions,
    deskew_image,
    remove_noise,
    get_image_dimensions,
    get_image_format,
    get_image_mode,
    get_image_info,
)